name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_call:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache: true

    - name: Download Go Modules
      run: go mod download

    - name: Run Unit Tests
      run: make test

  integration-tests:
    name: Integration Tests
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache: true

    - name: Download Go Modules
      run: go mod download

    - name: Pull Docker Images
      run: |
        docker pull motoserver/moto:5.1.22
        docker pull public.ecr.aws/lambda/provided:al2023

    - name: Run Integration Tests
      run: make test-integration
